In [3]:
from scipy.optimize import fsolve
import numpy as np
import matplotlib.pyplot as plt
import math

import tqdm

In [17]:
def get_cloud(bounds_t, bounds_x, cuts_t, cuts_x, solve):


    print(bounds_t, bounds_x, cuts_t, cuts_x, solve)

    m = len(bounds_t)
    n = len(bounds_x)

    lower_bounds_t = list(map(lambda x: x[0], bounds_t))
    upper_bounds_t = list(map(lambda x: x[1], bounds_t))

    print(lower_bounds_t)
    print(upper_bounds_t)

    if (m != len(cuts_t) or n != len(cuts_x)):
        raise ValueError("bounds and cuts must have the same length")
    
    # Create target space
    t = np.linspace(lower_bounds_t, upper_bounds_t, cuts_t[0])

    print(t)


In [20]:
get_cloud(((0, 1), (0, 1), (0, 10)), ((0, 1),), (10, 10, 10), (10,), None)

((0, 1), (0, 1), (0, 1)) ((0, 10),) (10, 10, 10) (10,) None
[0, 0, 0]
[1, 1, 1]
[[0.         0.         0.        ]
 [0.11111111 0.11111111 0.11111111]
 [0.22222222 0.22222222 0.22222222]
 [0.33333333 0.33333333 0.33333333]
 [0.44444444 0.44444444 0.44444444]
 [0.55555556 0.55555556 0.55555556]
 [0.66666667 0.66666667 0.66666667]
 [0.77777778 0.77777778 0.77777778]
 [0.88888889 0.88888889 0.88888889]
 [1.         1.         1.        ]]
